"""Public renderer-independent strategy analysis extension boundary."""

from f1_telemetry_charts.strategy.models import (
    STRATEGY_ANALYSIS_SCHEMA_VERSION,
    ComparisonResult,
    DeltaPoint,
    DescriptiveStatistics,
    PaceEvolutionResult,
    PitCycleResult,
    RaceTimeDeltaResult,
    RejoinContextResult,
    SectorEvolutionResult,
    StintSummary,
    StrategyAnalysisResult,
    StrategyExclusionPolicy,
    StrategyLap,
    StopExecutionResult,
    TrafficParticipant,
)
from f1_telemetry_charts.strategy.service import (
    compare_compounds,
    compare_pit_cycle,
    derive_strategy_analysis,
    descriptive_statistics,
    observed_pace_evolution,
    race_time_delta,
    strategy_metadata,
    strategy_policy_from_parameters,
    type7_quantile,
)

__all__ = [
    "STRATEGY_ANALYSIS_SCHEMA_VERSION",
    "ComparisonResult",
    "DeltaPoint",
    "DescriptiveStatistics",
    "PaceEvolutionResult",
    "PitCycleResult",
    "RaceTimeDeltaResult",
    "RejoinContextResult",
    "SectorEvolutionResult",
    "StintSummary",
    "StrategyAnalysisResult",
    "StrategyExclusionPolicy",
    "StrategyLap",
    "StopExecutionResult",
    "TrafficParticipant",
    "compare_compounds",
    "compare_pit_cycle",
    "derive_strategy_analysis",
    "descriptive_statistics",
    "observed_pace_evolution",
    "race_time_delta",
    "strategy_metadata",
    "strategy_policy_from_parameters",
    "type7_quantile",
]
